### ISSUE TITLE
Page blank when access besides page 1 with pagination

### ISSUE THREAD

**Issue by Deri-Kurniawan** [DreamTechTeam/Dreambinar-FE#4]
Page Blank when access pagination besides page 1 at [https://dreambinar.vercel.app/user/4](https://dreambinar.vercel.app/user/4)

Console Error:
```
TypeError: Cannot read properties of undefined (reading 'data')
    at Iu (User.js:177:37)
    at Eo (react-dom.production.min.js:167:137)
    at Cs (react-dom.production.min.js:197:258)
    at jl (react-dom.production.min.js:292:88)
    at bu (react-dom.production.min.js:280:389)
    at vu (react-dom.production.min.js:280:320)
    at gu (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at lu (react-dom.production.min.js:273:300)
    at Ha (react-dom.production.min.js:127:105)
```

**Comment by Ikram-Maulana** [comment]
Fixed Bug

- [x] Cause of Error: data to be used has been called before fetch is complete
